name = "機能鳥"
avatar = "images/profile1.jpg" # Avatar image. Default to "images/profile.webp".
bio = "バカです　何度もバカだって言ってるじゃないですか"
company = ""
location = "世界为一体的状态"
about = "/about/" # The external about page. The internal about page will be used if not set.
